--- 
apiVersion: v1
kind: Pod
metadata: 
  name: pod1
spec: 
  containers: 
    - 
      image: "busybox"
      name: busybox
      ports: 
        - 
          containerPort: 80
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      command: ['sh', '-c', 'echo PexonRocks!; sleep 600']
