--- 
apiVersion: v1
kind: Pod
metadata: 
  name: pod2
spec: 
  containers: 
    - 
      env: 
        - 
          name: MYSQL_ROOT_PASSWORD
          value: password
      image: "mysql"
      name: mysql
      ports: 
        - 
          containerPort: 3306
      resources: 
        limits: 
          cpu: "4"
          memory: 5Gi
        requests: 
          cpu: "0.6"
          memory: 2Gi
      volumeMounts: 
        - 
          mountPath: /var/lib/mysql
          name: pv0003
          readOnly: true
        - name: password
          secret:
          mountPath: /var/my-app
  volumes: 
    - name: password
      secret:
        secretName: password-d757ttfkt4
    - name: pv0003
      persistentVolumeClaim:
        claimName: pvc
