--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
spec: 
  replicas: 3
  selector:   
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers: 
        - 
          image: "nginx:1.18.0"
          name: nginx
          ports: 
            - 
              containerPort: 80
          resources: 
            limits: 
              cpu: "1"
              memory: 512Mi
            requests: 
              cpu: "0.2"
              memory: 256Mi
