apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  volumeName: pv0003
  storageClassName: pexon-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi